version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: bitaksi-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./mongo-data:/data/db

  mongo-express:

    # Thanks to this interface, the database can be viewed from the browser.

    image: mongo-express
    container_name: bitaksi-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongodb:27017/

      # panel login
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb