services:
  # --- DATABASE ---
  mongodb:
    image: mongo:6.0
    container_name: bitaksi-taxihub-mongo  
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - taxihub-network

  # --- DB GUI (Optional) ---
  mongo-express:
    image: mongo-express
    container_name: bitaksi-taxihub-express 
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - taxihub-network

  # --- DRIVER SERVICE ---
  driver-service:
    build:
      context: ./driver-service
      dockerfile: Dockerfile
    container_name: bitaksi-taxihub-backend 
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=taxidb
    depends_on:
      - mongodb
    networks:
      - taxihub-network

  # --- API GATEWAY ---
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: bitaksi-taxihub-gateway 
    ports:
      - "8000:8000"
    environment:
      - DRIVER_SERVICE_URL=http://driver-service:8080
      - JWT_SECRET=supersecretkey
    depends_on:
      - driver-service
    networks:
      - taxihub-network

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bitaksi-taxihub-frontend # <-- Yeni Ä°sim
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - gateway
    networks:
      - taxihub-network

networks:
  taxihub-network:
    driver: bridge

volumes:
  mongo-data: