services:
  # --- DATABASE ---
  mongodb:
    image: mongo:6.0
    container_name: bitaksi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bitaksi-network

  # --- DB GUI (Optional) ---
  mongo-express:
    image: mongo-express
    container_name: bitaksi-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - bitaksi-network

  # --- DRIVER SERVICE ---
  driver-service:
    build:
      context: ./driver-service
      dockerfile: Dockerfile
    container_name: bitaksi-driver-service
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=taxidb
    depends_on:
      - mongodb
    networks:
      - bitaksi-network

  # --- API GATEWAY ---
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: bitaksi-gateway
    ports:
      - "8000:8000"
    environment:
      - DRIVER_SERVICE_URL=http://driver-service:8080
      - JWT_SECRET=supersecretkey
    depends_on:
      - driver-service
    networks:
      - bitaksi-network

  # --- FRONTEND  ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bitaksi-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - gateway
    networks:
      - bitaksi-network

networks:
  bitaksi-network:
    driver: bridge

volumes:
  mongo-data: